=== wild-butterfly/xml-project/bryans-cafe.dtd
<!ELEMENT business (name, gif, sound, items)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT gif (#PCDATA)>
<!ELEMENT sound (#PCDATA)>
<!ELEMENT items (item*)>
<!ELEMENT item (name, price, description)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== wild-butterfly/xml-project/bryans-cafe.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>


<!DOCTYPE business SYSTEM "bryans-cafe.dtd">

<business>
    <name>Bryan's Caf√©</name>
    <gif>food.gif</gif>
    <sound>food_sound.mp3</sound>
    <items>
        <item>
            <name>Beetroot and Feta Salad</name>
            <price>$15.00</price>
            <description>Suitable for vegetarians, made with fresh beetroot</description>
        </item>
        <item>
            <name>Sourdough Rye Sandwich</name>
            <price>$18.00</price>
            <description>Cheese and salad sandwich made with organic, sourdough rye bread</description>
        </item>
        <item>
            <name>Spinach Pie and Salad</name>
            <price>$20.00</price>
            <description>Tasty pie with salad</description>
        </item>
        <item>
            <name>Feta Pancakes with Salad</name>
            <price>$19.50</price>
            <description>Tasty pancake filled with feta and salad.</description>
        </item>
    </items>
</business>
